"""
Copyright 2025. Brandon C. Tapia

MIT License
"""


def write_xyz(lammps_in, xyz_out="system.xyz"):
    """
    Writes an XYZ file from a LAMMPS data file (atom_style full),
    formatted for use with PoreBlazer.
    """

    atom_section = False
    atom_lines = []

    with open(lammps_in, "r", encoding="utf-8") as file:
        lines = file.readlines()

    for i, line in enumerate(lines):
        stripped = line.strip()
        columns = stripped.split()

        if stripped.startswith("Atoms"):
            atom_section = True
            continue

        if atom_section:
            if not columns:
                continue
            if columns[0].isalpha():
                break
            atom_lines.append(columns)

    with open(xyz_out, "w", encoding="utf-8") as file:
        file.write(f"{len(atom_lines)}\n")
        file.write("Generated by smithlab.poreblazer.write_xyz\n")
        for cols in atom_lines:
            atom_type = cols[2]
            x, y, z = cols[4], cols[5], cols[6]
            file.write(f"{atom_type} {x} {y} {z}\n")

    return


def write_forcefield(lammps_in, ff_out="ff.atoms"):

    mass_section = False
    pair_section = False

    kB = 1.9872e-3  # kcal/mol-K

    identifiers = []
    molwt = []
    energies = []
    sigma = []

    with open(lammps_in, "r", encoding="utf-8") as file:
        lines = file.readlines()

    for i, line in enumerate(lines):
        stripped = line.strip()
        columns = stripped.split()

        if stripped.startswith("Masses"):
            mass_section = True
            continue

        if stripped.startswith("Pair Coeffs"):
            pair_section = True
            mass_section = False
            continue

        if mass_section:
            if not columns:
                continue
            if columns[0].isalpha():
                mass_section = False
                continue

            identifiers.append(columns[0])
            molwt.append(columns[1])

        if pair_section:
            if not columns:
                continue
            if columns[0].isalpha():
                break

            energies.append(float(columns[1]) / kB)

            sigma.append(columns[2])

    with open(ff_out, "w", encoding="utf-8") as file:
        file.write(f"{len(identifiers)}\n")

        for i, identifier in enumerate(identifiers):
            file.write(
                f"{identifier} {float(sigma[i]):.4f} {float(energies[i]):.2f} {float(molwt[i]):.3f}\n"
            )

        file.write("! name of framework atom, diameter (LJ sigma) in A, epsilon in K, mol weight\n")

    return


def write_defaults(defaults="defaults.dat", settings=None):

    if settings is None:
        settings = {}

    ff = settings.setdefault("ff", "ff.atoms")
    he_D = settings.setdefault("he_D", 2.58)
    he_e = settings.setdefault("he_e", 10.22)
    he_T = settings.setdefault("he_T", 298)
    he_cutoff = settings.setdefault("he_cutoff", 12.8)
    probe_D = settings.setdefault("probe_D", 3.314)
    trials = settings.setdefault("trials", 500)
    cubelet_size = settings.setdefault("cubelet_size", 0.2)
    largest_pore_D = settings.setdefault("largest_pore_D", 15)
    bin_size = settings.setdefault("bin_size", 0.25)
    rand_num = settings.setdefault("rand_num", 21908391)
    vis_network = settings.setdefault("vis_network", 0)

    with open(defaults, "w", encoding="utf-8") as file:
        file.write(f"{ff}\n{he_D}, {he_e}, {he_T}, {he_cutoff}\n{probe_D}\n{trials}\n{cubelet_size}\n{largest_pore_D}, {bin_size}\n{rand_num}\n{vis_network}\n\n")
        file.write("! Default forcefield\n")
        file.write(
            "! Helium atom sigma (A), helium atom epsilon (K), temperature (K), cutoff distance (A)\n"
        )
        file.write("! Probe atom sigma (A)\n")
        file.write("! Number of samples per atom for the surface area calculation\n")
        file.write("! Cubelet size (A)\n")
        file.write("! Largest anticipated pore diameter (A), size of the bin for PSD (A)\n")
        file.write("! Random number seed\n")
        file.write("! Visualization options: 1 -xyz, 2 - grd, 3 - both; 0 - none\n\n")
        file.write("! Do not change these values unless you know what you are doing\n")

    return


def write_input(lammps_in, input="input.dat", xyz_out="system.xyz"):

    count = 0 
    with open(lammps_in, "r", encoding="utf-8") as file:
        lines = file.readlines()

    for line in lines:
        stripped = line.strip()
        columns = stripped.split()
        
        if stripped.endswith("xhi"):
            x_length = float(columns[1]) - float(columns[0])
            count += 1
        elif stripped.endswith("yhi"):
            y_length = float(columns[1]) - float(columns[0])
            count += 1
        elif stripped.endswith("zhi"):
            z_length = float(columns[1]) - float(columns[0])
            count += 1

        if count == 3:
            break

    with open(input, "w", encoding="utf-8") as file:
        file.write(f"{xyz_out}\n{x_length} {y_length} {z_length}\n90 90 90")

    return


def setup_pb(lammps_in, settings=None, xyz="system.xyz", ff_out="ff.atoms", defaults="defaults.dat", input_file="input.dat"):

    write_xyz(lammps_in, xyz)
    write_forcefield(lammps_in, ff_out)
    write_defaults(defaults, settings)
    write_input(lammps_in, input_file, "system.xyz") #TODO: allow for path if needed

    return
