"""
Helper functions for the qforce package
https://pubs.acs.org/doi/10.1021/acs.jctc.1c00195
https://qforce.readthedocs.io/en/latest/
https://github.com/selimsami/qforce
"""


def make_ext_lj(top_in, type_idx=None):
    """Makes the ext_lj parameter file from a given *.top GROMACS topology file.
    Tested with topology files generated by MKTOP.pl"""

    with open(top_in, "r") as f:
        lines = f.readlines()

    ext_lj_params = []
    in_atoms = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        cols = stripped.split()

        if stripped.lower().replace(" ", "") == "[atoms]":
            in_atoms = True
            continue

        if in_atoms and stripped.startswith(";"):
            # Need to account for the first col being the comment marker ;
            type_idx = cols.index("type") - 1
            continue

        if in_atoms and cols[0].isdigit():
            if type_idx is None:
                raise ValueError("Could not automatically determine type_idx. Please specify manually as type_idx=...")

            atom_type = cols[type_idx]
            ext_lj_params.append(atom_type)

        elif in_atoms:
            break

    # write ext_lj parameter file
    with open("ext_lj", "w") as f:
        for atom_type in ext_lj_params:
            f.write(f"{atom_type}\n")
