import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.interpolate import UnivariateSpline, CubicSpline, PchipInterpolator
from scipy.optimize import curve_fit

def compute_bi(
    dist_file,
    temperature,
    dist_type,
    shift_mode="auto",
    output_file=None,
    min_prob=1e-12,
    prob_threshold=1e-8,
    plot=True,
    ):
    """Compute volume-normalized BI potentials from VOTCA dist.new files.

    Args:
        dist_file: Distribution file (dist.new) generated by Votca
        temperature: Temperature in K
        dist_type: Type of distribution (bond, angle, dihedral, nonbond)
        output_file: 
        shift_mode: How a shift should be applied to the potential
            "auto"   -> "min" for bonded, "cutoff" for nonbonded
            "min"    -> min(U) = 0
            "cutoff" -> U(last) = 0
            None     -> no shifting
        min_prob: Minimum probability to use to remove ln blowup
        prob_threshhold: 
    """

    kB = 0.00831446261815324  # kJ/mol/K

    dist_type = dist_type.lower()

    data = np.loadtxt(
        dist_file,
        comments=["#", "@"],
        usecols=(0, 1),
    )

    x = data[:, 0]
    prob = data[:, 1]

    prob_safe = np.clip(prob, min_prob, None)

    if dist_type == "bond":
        geom = 4.0 * np.pi * x**2
        prob_normalized = prob_safe / np.clip(geom, min_prob, None)

    elif dist_type == "angle":
        geom = np.sin(x)  # assumes x is in radians
        prob_normalized = prob_safe / np.clip(geom, min_prob, None)

    elif dist_type in ["dihedral", "torsion", "nonbond", "nonbonded"]:
        prob_normalized = prob_safe

    else:
        raise ValueError(
            "dist_type must be one of: bond, angle, dihedral, nonbond"
        )

    U = -kB * temperature * np.log(prob_normalized)

    # mask truly unsampled regions
    U[prob <= 0] = np.nan

    if shift_mode == "auto":
        if dist_type in ["bond", "angle", "dihedral", "torsion"]:
            shift_mode = "min"
        elif dist_type in ["nonbond", "nonbonded"]:
            shift_mode = "cutoff"

    if shift_mode == "min":
        mask = (prob > prob_threshold) & np.isfinite(U)
        if np.any(mask):
            U -= np.nanmin(U[mask])

    elif shift_mode == "cutoff":
        valid = np.where(np.isfinite(U))[0]
        if len(valid) > 0:
            U -= U[valid[-1]]

    elif shift_mode is None:
        pass

    else:
        raise ValueError("shift_mode must be 'auto', 'min', 'cutoff', or None")

    df = pd.DataFrame(
        {
            "x": x,
            "probability_raw": prob,
            "probability_normalized": prob_normalized,
            "potential_kj_mol": U,
        }
    )

    if output_file is not None:
        df.to_csv(output_file, sep=" ", index=False, float_format="%.10g")

    if plot:
        fig, axes = plt.subplots(1, 3, figsize=(15, 4))

        axes[0].plot(x, prob)
        axes[0].set_xlabel("x")
        axes[0].set_ylabel("raw probability")

        axes[1].plot(x, prob_normalized)
        axes[1].set_xlabel("x")
        axes[1].set_ylabel("normalized probability")

        axes[2].plot(x, U)
        axes[2].set_xlabel("x")
        axes[2].set_ylabel("U(x) [kJ/mol]")

        plt.tight_layout()
        plt.show()

    return df


def compute_fm(
    force_file,
    shift_mode,
    output_file=None,
    plot=True,
):
    """Integrates VOTCA force-matching .force files into potentials.

    Args:
        force_file: VOTCA .force file from csg_fmatch.
        output_file: Optional output file.
        shift_mode:
            "min"    -> min(U) = 0
            "cutoff" -> U(last) = 0
            None     -> no shifting
        plot: Whether to plot force and potential.
    """

    data = np.genfromtxt(
        force_file,
        comments="#",
        usecols=(0, 1, 2),
        names=True,
    )
    x = data["x"]
    force = data["force"]
    error = data["error"]

    U = np.zeros_like(x)

    for i in range(1, len(x)):
        dx = x[i] - x[i - 1]
        avg_force = 0.5 * (force[i] + force[i - 1])
        U[i] = U[i - 1] - avg_force * dx

    if shift_mode == "min":
        U -= np.nanmin(U)

    elif shift_mode == "cutoff":
        U -= U[-1]

    elif shift_mode is None:
        pass

    else:
        raise ValueError("shift_mode must be 'min', 'cutoff', or None")

    df = pd.DataFrame(
        {
            "x": x,
            "force": force,
            "error": error,
            "potential_kj_mol": U,
        }
    )

    if output_file is not None:
        df.to_csv(output_file, sep=" ", index=False, float_format="%.10g")

    if plot:
        plt.plot(x, force)
        plt.xlabel("x")
        plt.ylabel("force")
        plt.show()

        #plt.plot(x, error)
        #plt.xlabel("x")
        #plt.ylabel("force error")
        #plt.show()

        plt.plot(x, U)
        plt.xlabel("x")
        plt.ylabel("U(x) [kJ/mol]")
        plt.show()

    return df


def fit_spline(
    data,
    x_col="x",
    U_col="potential_kj_mol",
    force_col=None,
    smoothing=0.0,
    method="pchip",
    extrapolate=False,
    output_file=None,
    plot=False,
):
    """
    Fit a continuous interpolation/spline to U(x), compute F(x) = -dU/dx,
    and optionally compare interpolated U/F to file values.

    Recommended:
        method="pchip"

    PCHIP is shape-preserving and avoids unphysical cubic spline overshoot.
    """

    if isinstance(data, (str, Path)):
        df = pd.read_csv(data, sep=r"\s+", comment="#")
    else:
        df = data.copy()

    x = df[x_col].to_numpy(dtype=float)
    U = df[U_col].to_numpy(dtype=float)

    mask = np.isfinite(x) & np.isfinite(U)

    if force_col is not None and force_col in df.columns:
        F_raw = df[force_col].to_numpy(dtype=float)
        mask &= np.isfinite(F_raw)
    else:
        F_raw = None

    x = x[mask]
    U = U[mask]

    if F_raw is not None:
        F_raw = F_raw[mask]

    order = np.argsort(x)
    x = x[order]
    U = U[order]

    if F_raw is not None:
        F_raw = F_raw[order]

    x_unique, idx = np.unique(x, return_index=True)
    x = x_unique
    U = U[idx]

    if F_raw is not None:
        F_raw = F_raw[idx]

    if method == "spline":
        spl = UnivariateSpline(x, U, s=smoothing)

    elif method == "cubic":
        spl = CubicSpline(x, U, extrapolate=extrapolate)

    elif method == "pchip":
        spl = PchipInterpolator(x, U, extrapolate=extrapolate)

    else:
        raise ValueError("method must be 'spline', 'cubic', or 'pchip'")

    def U_func(x_eval):
        x_eval = np.asarray(x_eval, dtype=float)
        if not extrapolate:
            x_eval = np.clip(x_eval, x.min(), x.max())
        return spl(x_eval)

    def F_func(x_eval):
        x_eval = np.asarray(x_eval, dtype=float)
        if not extrapolate:
            x_eval = np.clip(x_eval, x.min(), x.max())
        return -spl.derivative()(x_eval)

    U_spline = U_func(x)
    F_spline = F_func(x)

    out = pd.DataFrame(
        {
            "x": x,
            "potential_kj_mol": U,
            "potential_spline_kj_mol": U_spline,
            "force_spline_kj_mol_per_x": F_spline,
        }
    )

    if F_raw is not None:
        out["force_raw"] = F_raw

    if output_file is not None:
        out.to_csv(output_file, sep=" ", index=False, float_format="%.10g")

    if plot:
        fig, axes = plt.subplots(1, 2, figsize=(10, 4))

        axes[0].plot(x, U, "o", label="raw U")
        axes[0].plot(x, U_spline, "-", label=f"{method} U")
        axes[0].set_xlabel("x")
        axes[0].set_ylabel("U(x) [kJ/mol]")
        axes[0].legend()

        if F_raw is not None:
            axes[1].plot(x, F_raw, "o", label="raw force")

        axes[1].plot(x, F_spline, "-", label=f"{method} force")
        axes[1].set_xlabel("x")
        axes[1].set_ylabel("F(x) = -dU/dx")
        axes[1].legend()

        plt.tight_layout()
        plt.show()

    return out, U_func, F_func


def write_lammps_table(
    outfile,
    keyword,
    U_func,
    table_type,
    x_min,
    x_max,
    F_func=None,
    n=1000,
    energy_unit_scale=0.239006,
    x_unit_scale="auto",
    zero_minimum=True,
):
    """
    Write a LAMMPS table file.

    For units real:
        energy_unit_scale = 0.239006 converts kJ/mol -> kcal/mol

    Assumed input units:
        bond/pair x: nm
        angle/dihedral x: radians

    Written units:
        bond/pair x: Angstrom
        angle/dihedral x: degrees
    """

    table_type = table_type.lower()

    if x_unit_scale == "auto":
        if table_type in ["pair", "bond"]:
            x_unit_scale = 10.0
        elif table_type in ["angle", "dihedral"]:
            x_unit_scale = 180.0 / np.pi
        else:
            raise ValueError("table_type must be bond, pair, angle, or dihedral")

    outfile = Path(outfile)

    sampled_min = x_min
    sampled_max = x_max

    if table_type == "pair":
        x_inner = 0.01   # nm = 0.1 Å
        x = np.linspace(x_inner, sampled_max, n)

    elif table_type == "bond":
        x_inner = 0.01   # nm = 0.1 Å
        x_outer = 1.00   # nm = 10 Å
        x = np.linspace(x_inner, x_outer, n)

    elif table_type == "angle":
        x = np.linspace(0.0, np.pi, n)

    elif table_type == "dihedral":
        x = np.linspace(x_min, x_max, n)

    else:
        raise ValueError("table_type must be bond, pair, angle, or dihedral")

    x_write = x * x_unit_scale

    if table_type in ["pair", "bond", "angle"]:
        U = energy_unit_scale * U_func(np.clip(x, sampled_min, sampled_max))
    else:
        U = energy_unit_scale * U_func(x)

    if zero_minimum:
        U = U - np.nanmin(U)

    if table_type == "pair":
        low_mask = x < sampled_min

        if np.any(low_mask):
            U_at_sampled_min = U[np.argmin(np.abs(x - sampled_min))]
            U_wall = max(100.0, 500.0 * np.nanmax(np.abs(U)))

            s = (sampled_min - x[low_mask]) / (sampled_min - x_inner)
            U[low_mask] = U_at_sampled_min + U_wall * s**1.2

    elif table_type == "bond":
        wall_height = 10.0 * np.nanmax(U)

        low_mask = x < sampled_min
        high_mask = x > sampled_max

        U[low_mask] = wall_height
        U[high_mask] = wall_height

    elif table_type == "angle":
        wall_height = 2.0 * np.nanmax(U)

        low_mask = x < sampled_min
        high_mask = x > sampled_max

        U[low_mask] = wall_height
        U[high_mask] = wall_height

    # force from final modified potential
    F = -np.gradient(U, x_write)

    with outfile.open("w", newline="\n") as f:
        f.write(f"# LAMMPS {table_type} table\n")
        f.write(f"# keyword: {keyword}\n\n")
        f.write(f"{keyword}\n")

        if table_type == "pair":
            f.write(f"N {n} R {x_write[0]:.10g} {x_write[-1]:.10g}\n\n")
        else:
            f.write(f"N {n}\n\n")

        for i, (xi, ui, fi) in enumerate(zip(x_write, U, F), start=1):
            f.write(f"{i:8d} {xi:18.10f} {ui:18.10f} {fi:18.10f}\n")


def fit_harmonic(
    data,
    x_col="x",
    U_col="potential_spline_kj_mol",
    fit_window=0.05,
    x0=None,
    output_units="bond",
    plot=False,
):
    """
    Fit a local harmonic potential:

        U(x) = 0.5 * k * (x - x0)^2 + C

    Args:
        data:
            DataFrame containing x and U columns.
        fit_window:
            Half-width around the minimum used for fitting.
            Bonds: nm, e.g. 0.03-0.08
            Angles: radians, e.g. 0.1-0.3
        x0:
            Optional fixed equilibrium value. If None, uses minimum of U.
        output_units:
            "bond"  -> x in nm, k in kJ/mol/nm^2
            "angle" -> x in radians, k in kJ/mol/rad^2, theta0 also printed in deg
        plot:
            Plot spline potential and harmonic fit.

    Returns:
        dict with x0, k, C, fit range, and optional angle degrees.
    """

    df = data.copy()

    x = df[x_col].to_numpy(dtype=float)
    U = df[U_col].to_numpy(dtype=float)

    mask = np.isfinite(x) & np.isfinite(U)
    x = x[mask]
    U = U[mask]

    order = np.argsort(x)
    x = x[order]
    U = U[order]

    if x0 is None:
        x0 = x[np.argmin(U)]

    fit_mask = (x >= x0 - fit_window) & (x <= x0 + fit_window)

    if np.count_nonzero(fit_mask) < 3:
        raise ValueError(
            "Not enough points in fit window. Increase fit_window or check x spacing."
        )

    x_fit = x[fit_mask]
    U_fit = U[fit_mask]

    # Fit U = a*(x-x0)^2 + b*(x-x0) + c
    dx = x_fit - x0
    a, b, C = np.polyfit(dx, U_fit, 2)

    # Harmonic convention: U = 0.5*k*(x-x0)^2
    k = 2.0 * a

    result = {
        "x0": x0,
        "k": k,
        "C": C,
        "linear_term": b,
        "fit_window": fit_window,
        "fit_min": x_fit.min(),
        "fit_max": x_fit.max(),
    }

    if output_units == "angle":
        result["theta0_deg"] = np.degrees(x0)
        result["gromacs_theta0"] = np.degrees(x0)
        result["gromacs_k"] = k

    elif output_units == "bond":
        result["gromacs_r0"] = x0
        result["gromacs_k"] = k

    else:
        raise ValueError("output_units must be 'bond' or 'angle'")

    if plot:
        x_dense = np.linspace(x_fit.min(), x_fit.max(), 300)
        U_harm = 0.5 * k * (x_dense - x0) ** 2 + C

        plt.plot(x, U, label="spline U")
        plt.plot(x_fit, U_fit, "o", label="fit points")
        plt.plot(x_dense, U_harm, label="harmonic fit")
        plt.xlabel("x")
        plt.ylabel("U(x) [kJ/mol]")
        plt.legend()
        plt.tight_layout()
        plt.show()

    return result

def fit_morse(
    data,
    x_col="x",
    U_col="potential_spline_kj_mol",
    fit_window=0.03,
    x0=None,
    plot=False,
):
    df = data.copy()

    x = df[x_col].to_numpy(dtype=float)
    U = df[U_col].to_numpy(dtype=float)

    mask = np.isfinite(x) & np.isfinite(U)
    x = x[mask]
    U = U[mask]

    order = np.argsort(x)
    x = x[order]
    U = U[order]

    if x0 is None:
        x0 = x[np.argmin(U)]

    fit_mask = (x >= x0 - fit_window) & (x <= x0 + fit_window)
    x_fit = x[fit_mask]
    U_fit = U[fit_mask]

    U_fit = U_fit - np.min(U_fit)

    def morse(r, De, beta, r0, C):
        return De * (1.0 - np.exp(-beta * (r - r0)))**2 + C

    # approximate harmonic curvature near minimum:
    # k ≈ 2 De beta^2
    p0 = [50.0, 30.0, x0, 0.0]

    bounds = (
        [1e-8, 1e-8, x0 - fit_window, -np.inf],
        [np.inf, np.inf, x0 + fit_window, np.inf],
    )

    popt, pcov = curve_fit(
        morse,
        x_fit,
        U_fit,
        p0=p0,
        bounds=bounds,
        maxfev=10000,
    )

    De, beta, r0, C = popt

    result = {
        "r0": r0,
        "De": De,
        "beta": beta,
        "C": C,
        "gromacs_funct": 3,
        "gromacs_b0": r0,
        "gromacs_D": De,
        "gromacs_beta": beta,
    }

    if plot:
        x_dense = np.linspace(x_fit.min(), x_fit.max(), 400)
        plt.plot(x, U - np.nanmin(U), label="spline U")
        plt.plot(x_fit, U_fit, "o", label="fit points")
        plt.plot(x_dense, morse(x_dense, *popt), label="Morse fit")
        plt.xlabel("r [nm]")
        plt.ylabel("U(r) [kJ/mol]")
        plt.legend()
        plt.tight_layout()
        plt.show()

    return result